# Generated by Django 4.2.3 on 2023-07-18 08:34

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=image_app.models.image_upload_path),
        ),
    ]
